---
- name: Configure SNMP on cEOS devices
  hosts: ceos
  connection: network_cli
  gather_facts: true
  become: true
  become_method: ansible.netcommon.enable

  vars_files:
    - group_vars/secrets.yml

  tasks:
    - name: Show which user is being used
      ansible.builtin.debug:
        msg: "Logging in as {{ ansible_user }}"

    - name: Set SNMP Configuration
      arista.eos.eos_config:
        lines:
          - snmp-server location {{ location }}
          - snmp-server community {{ community }} ro
        save_when: always
